# Generated by Django 5.2.8 on 2025-11-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diaryentry_view_project_view_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='view',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='view',
            new_name='views',
        ),
    ]
