# Generated by Django 5.2.8 on 2025-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_view_diaryentry_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='upload',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
